### ISSUE TITLE
Parks.csv has ambiguous 'city' entries for New York stadiums.

### ISSUE THREAD

**Issue by Dreslough** [chadwickbureau/baseballdatabank#68]
Some entries just specify the borough ("Brooklyn", "Queens") while modern stadiums only show "New York".

Updated file attached (all instances of "New York" replaced with the correct borough).
[Parks.csv.xlsx](https://github.com/chadwickbureau/baseballdatabank/files/1549201/Parks.csv.xlsx)

**Comment by horwitz** [comment]
Were, e.g., the Brooklyn-labeled parks from a time when they would actually be in the City of Brooklyn (before it became a part of New York City in 1898)?

**Comment by tturocy** [comment]
Well, I disagree that it's "ambiguous." Brooklyn and Queens have histories as separate political entities prior to annexation by the City of New York. Although I can see an argument to list all of these as "New York" (the current name of the geographical areas), it actually gives more information to present them as Brooklyn and Queens.  So I do not have a problem with the convention being used.

In any event, this is a Retrosheet-derived file, and as such this is not the place to make a change (because any change would just be overwritten by a future pull from Retrosheet).  You can take this up with David Smith, and if he feels it's a change he wants to make, then it will propagate.

As a tip for future contributions: Attaching an Excel workbook is simply a non-starter, as it imposes far too much unnecessary work on maintainers.  I'm not going to leaf through a file to try to figure out what has changed (and to make sure that something unintended hasn't changed).  The files are hosted in a version control system precisely to enable pull requests to be made so that inefficient and unnecessary work does not have to be done by maintainers.  In future please use this - although noting that an increasing proportion of files are automatically generated.

**Comment by Dreslough** [comment]
On 12/12/2017 12:07 PM, Ted Turocy wrote:
>
> Well, I disagree that it's "ambiguous." Brooklyn and Queens have 
> histories as separate political entities prior to annexation by the 
> City of New York. Although I can see an argument to list all of these 
> as "New York" (the current name of the geographical areas), it 
> actually gives more information to present them as Brooklyn and 
> Queens. So I do not have a problem with the convention being used.
>

It appears that I didn't express myself clearly. I agree with your 
stance that "Brooklyn" are "Queens" are preferable, because they provide 
more information. What I had done in the attached file was changed "New 
York" to the correct borough. I certainly wasn't advocating changing 
anything to "New York".

> In any event, this is a Retrosheet-derived file, and as such this is 
> not the place to make a change (because any change would just be 
> overwritten by a future pull from Retrosheet). You can take this up 
> with David Smith, and if he feels it's a change he wants to make, then 
> it will propagate.
>
Will do. Thanks!

> As a tip for future contributions: Attaching an Excel workbook is 
> simply a non-starter, as it imposes far too much unnecessary work on 
> maintainers. I'm not going to leaf through a file to try to figure out 
> what has changed (and to make sure that something unintended hasn't 
> changed). The files are hosted in a version control system precisely 
> to enable pull requests to be made so that inefficient and unnecessary 
> work does not have to be done by maintainers. In future please use 
> this - although noting that an increasing proportion of files are 
> automatically generated.
>
I had a corrected .csv file, but GitHub wouldn't accept it -- or a .txt 
file -- as an attachment. That's the only reason I attached an .xlsx 
file -- it was the most similar acceptable format.

Clay

**Comment by tturocy** [comment]
The unnecessarily complication has to do with attaching a file in the first instance, not per se that it was Excel.  The way to do it is a pull request, see https://help.github.com/articles/about-pull-requests/
