### ISSUE TITLE
2017 SQL update

### ISSUE THREAD

**Issue by dbodemer** [chadwickbureau/baseballdatabank#80]
Will there be a sql import developed to load the 2017 data?

**Comment by tturocy** [comment]
This is outside the scope of the project, as of course CSV can be imported into just about anything, including any RDBMS, so a SQL version would be redundant.

**Comment by rippinrobr** [comment]
@dbodemer what database are you looking to use?  I can get you sql for sqlite and postgres.

**Comment by dbodemer** [comment]
I am using MySQL

**Comment by rippinrobr** [comment]
@dbodemer  Here you go. The zip file has a data backup and a schema file.  Just so you are aware there are 14 records that aren't in the `pitchingpost table` due to MySQL's decision to not support the `inf` value for infinity.  Each of the 14 records are for pitches with an ERA of infinity
[mysql-backup-2017.4-9f91176_baseballdatabank.zip](https://github.com/chadwickbureau/baseballdatabank/files/1913136/mysql-backup-2017.4-9f91176_baseballdatabank.zip)

I regularly load updates to the baseballdatabank repo in SQLite, Postgres and MySQL databases and share their backkups at my [baseball-stats-db](https://github.com/rippinrobr/baseball-stats-db). I will be adding Retrosheet data to these releases also.

**Comment by dbodemer** [comment]
Thank you, I will try this tonight.
