### ISSUE TITLE
Created a DoltHub Mirror

### ISSUE THREAD

**Issue by timsehn** [chadwickbureau/baseballdatabank#99]
We are building a relational database with Git semantics called Dolt (https://github.com/liquidata-inc/dolt). This project is ideal for it. 

I went ahead and created a mirror of this database on DoltHub (GitHub for Dolt):

https://www.dolthub.com/repositories/Liquidata/baseball-databank

I also wrote an import job so when master is updated here, it will sync to Dolt (https://github.com/liquidata-inc/liquidata-etl-jobs/tree/master/airflow_dags/baseball-databank).

If you have anyone who wants to get the data in SQL form, Dolt would be ideal for them.

**Comment by tturocy** [comment]
If you do this, do be aware that we do not guarantee referential integrity on references to People between releases of the free public version.  This occurs because we do update People daily, but other tables are only updated annually in the public version.  This occurs very rarely - in recent history perhaps once every 18 months on average.

I suppose this might be useful for some users if they would like an alternative way to trace the history of data.  However the files in this repository are actually computed, derived files based on a much larger dataset that's version-controlled in a different way; using this repository is just a simple way to post the data and make it easy to access without us having to do much work.

**Comment by timsehn** [comment]
Fair enough. Thanks for checking it out.

--Tim
